//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class SimpleLogUnitWrap {
  err: ErrorCode;
  lowwater: number;
  highwater: number;
  trimmark: number;
  ckmark: number;
  ctnt: string[];
  bmap: string;

  constructor(args?: { err: ErrorCode; lowwater: number; highwater: number; trimmark: number; ckmark: number; ctnt: string[]; bmap: string; });
}
