//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class SimpleLogUnitConfigServiceClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  probe(): void;

  probe(, callback: Function): void;

  phase2b(config: string): ErrorCode;

  phase2b(config: string, callback: Function): void;

  phase1b(masterid: number): string;

  phase1b(masterid: number, callback: Function): void;

  rebuild(): SimpleLogUnitWrap;

  rebuild(, callback: Function): void;

  kill(): void;

  kill(, callback: Function): void;
}
