//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class StreamSequence {
  position: number;
  totalTokens: number;

  constructor(args?: { position: number; totalTokens: number; });
}
